try github action

diff --git a/.github/workflows/biome-check.yml b/.github/workflows/biome-check.yml
--- a/.github/workflows/biome-check.yml
+++ b/.github/workflows/biome-check.yml
@@ -21,9 +21,9 @@ jobs:
       - name: Install dependencies
         run: npm ci
 
-      - name: Run Biome Check
+      - name: Run Biome format
         run: |
-          if ! npx biome check; then
-            echo "::error::🚨 Biome check failed! Please fix formatting issues by running 'npx biome format' locally.";
+          if ! npm run format; then
+            echo "::error::🚨 Biome check failed! Please fix formatting issues by running 'npm run format' locally.";
             exit 1;
           fi
